new WOW().init();
  function modalToggle(){
    var modal = '<!-- Modal --> <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true"> <div class="modal-dialog" role="document"> <div class="modal-content"> <div class="modal-header"> <h5 class="modal-title">40 days praise challenge</h5> <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button> </div> <div class="modal-body"> <div class="container-fluid"> <div class="row"> <div class="col"> <p> New international version speaking to one another with psalms, hymns and songs from the spirit. Sing and make music from your heart to the LORD </p> </div> </div> <div class="row"> <div class="col"> <div class="timer time d-flex text-center justify-content-center"> <h3>Next Challenge In</h3> <div class="timer-row d-flex justify-content-center"> <div class="d-flex"><span class="domDays">00</span> <span>Days</span></div> <div class="d-flex"><span class="domHour">00</span> <span>Hours</span></div> <div class="d-flex"><span class="domMin">00</span> <span>Minutes</span></div> <div class="d-flex"><span class="domSec">00</span> <span>Seconds</span></div> </div> </div> </div> </div> <style> /* timer */ .timer { flex-direction: column; } .time { background: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.7)), url(../img/mike.jpg) no-repeat center; background-size: cover; height: 15rem; } .timer h3 { color: #fff !important; font-weight: 400; } .timer-row>div { flex-direction: column; margin: 0 0.2rem; line-height: 1; } .timer span:first-child { font-size: 3rem; color: orangered; } .timer span:last-child { text-transform: uppercase; font-size: .9rem; color: white; } #headerFoot { box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.1); position: relative; top: -3%; z-index: 500; } </style> </div> <div class="modal-footer"> <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> <a href="https://www.gppcroshodi.ga/praisechallenge/" class="btn btn-primary">View now</a> </div> </div> </div> </div> </div> <!-- Button trigger modal --> <button id="mbtn" type="button" style="display:none" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modelId"> </button>';
    var src = document.createElement('script');
    src.innerHTML = '    var date; setInterval(() => { date = new Date(), day = date.getDate() + 21, hour = 23 - date.getHours(), min = 59 - date.getMinutes(), sec = 59 - date.getSeconds(); }, 1000); function countDown() { var domHour = Array.from(document.querySelectorAll(".domHour")), domDay = document.getElementById("domDay"), domMin = Array.from(document.querySelectorAll(".domMin")), domSec = Array.from(document.querySelectorAll(".domSec")); var date = new Date(), day = date.getDate() - 9, hour = 23 - date.getHours(), min = 59 - date.getMinutes(), sec = 59 - date.getSeconds(); if (domDay) domDay.textContent = ` Day ${dec(day)} up next`; function dec(num) { if (num < 10) { return "0" + num; } else return num; }  if (hour >= 23 && min >= 59 - 30) { day--; hour = 0; min = 0; sec = 0; if (domDay) domDay.textContent = " Day " + day + " in progress"; } function loop(unit, value) { unit.forEach(cur => { cur.textContent = dec(value) }) } loop(domHour, hour); loop(domMin, min); loop(domSec, sec); } setInterval(() => { countDown(); var date_ = 10 - new Date().getDate(); if (date_ < 10 && date_ > 0) { document.querySelector(".domDays").innerHTML = date_; document.querySelector(".timer h3").innerHTML = "First challenge in"; } else if (date_ == 0) { document.querySelector(".timer h3").innerHTML = "First challenge in"; document.querySelector(".domDays").parentElement.innerHTML = "" } else if (date_ < 0) { if (hour >= 23 && min >= 59 - 30) { document.querySelector(".timer h3").innerHTML = " Day " + (day - 1) + " in progress"; } else document.querySelector(".timer h3").innerHTML = "Next challenge in"; document.querySelector(".domDays").parentElement.innerHTML = "" } }, 1000)';
    body = document.querySelector('body');
    body.append(src);
    body.innerHTML += modal
    setTimeout(() => {
      mbtn.click();
    }, 20000);
    }
    

